### PR TITLE
Added support for docker CentOS7.3

### PR DESCRIPTION
**Pull request by nickurt**
Based on the [CentOS-Dockerfiles](https://github.com/CentOS/CentOS-Dockerfiles) and the Fedora-scripts ...

### CODE REVIEW

**Comment by TheNodi** [comment]
Great work, thank you.

I've added PHP5.6 repo since it was installing PHP5.4 and Valet requires 5.6+. I'm gonna merge and push it to the Docker Hub.

**Comment by nickurt** [comment]
Sorry, I forgot about the PHP-version. Is it not better to test it on "remi-php70" or "remi-php71"?

**Comment by TheNodi** [comment]
I try to keep the stock version or as close to it as possible to hopefully cover most of the distro users.

There're Integration tests that runs on every php version from 5.6 to 7.1, they should assert the raw commands passed to the OS are correct. Functional tests usually spots errors that aren't related to php version. 

In practice it would be nice to test all OS-PHP combinations, but it means 18 docker boxes (and probably more going on) and an abuse of the free Travis CI plan. Honestly since we're not making a production-oriented tool I think this gives a sufficient test coverage.

**Comment by nickurt** [comment]
Understandable, thank you.

**Pull request merged**
